// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: api.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CoretexApi_SubmitJob_FullMethodName    = "/coretex.v1.CoretexApi/SubmitJob"
	CoretexApi_GetJobStatus_FullMethodName = "/coretex.v1.CoretexApi/GetJobStatus"
)

// CoretexApiClient is the client API for CoretexApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoretexApiClient interface {
	SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error)
	GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error)
}

type coretexApiClient struct {
	cc grpc.ClientConnInterface
}

func NewCoretexApiClient(cc grpc.ClientConnInterface) CoretexApiClient {
	return &coretexApiClient{cc}
}

func (c *coretexApiClient) SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error) {
	out := new(SubmitJobResponse)
	err := c.cc.Invoke(ctx, CoretexApi_SubmitJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coretexApiClient) GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error) {
	out := new(GetJobStatusResponse)
	err := c.cc.Invoke(ctx, CoretexApi_GetJobStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoretexApiServer is the server API for CoretexApi service.
// All implementations must embed UnimplementedCoretexApiServer
// for forward compatibility
type CoretexApiServer interface {
	SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error)
	GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error)
	mustEmbedUnimplementedCoretexApiServer()
}

// UnimplementedCoretexApiServer must be embedded to have forward compatible implementations.
type UnimplementedCoretexApiServer struct {
}

func (UnimplementedCoretexApiServer) SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitJob not implemented")
}
func (UnimplementedCoretexApiServer) GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedCoretexApiServer) mustEmbedUnimplementedCoretexApiServer() {}

// UnsafeCoretexApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoretexApiServer will
// result in compilation errors.
type UnsafeCoretexApiServer interface {
	mustEmbedUnimplementedCoretexApiServer()
}

func RegisterCoretexApiServer(s grpc.ServiceRegistrar, srv CoretexApiServer) {
	s.RegisterService(&CoretexApi_ServiceDesc, srv)
}

func _CoretexApi_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoretexApiServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoretexApi_SubmitJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoretexApiServer).SubmitJob(ctx, req.(*SubmitJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoretexApi_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoretexApiServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoretexApi_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoretexApiServer).GetJobStatus(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// coretexApi_ServiceDesc is the grpc.ServiceDesc for coretexApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoretexApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coretex.v1.CoretexApi",
	HandlerType: (*CoretexApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitJob",
			Handler:    _CoretexApi_SubmitJob_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _CoretexApi_GetJobStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
