// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: context.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ContextEngine_BuildWindow_FullMethodName  = "/coretex.v1.ContextEngine/BuildWindow"
	ContextEngine_UpdateMemory_FullMethodName = "/coretex.v1.ContextEngine/UpdateMemory"
	ContextEngine_IngestRepo_FullMethodName   = "/coretex.v1.ContextEngine/IngestRepo"
)

// ContextEngineClient is the client API for ContextEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContextEngineClient interface {
	BuildWindow(ctx context.Context, in *BuildWindowRequest, opts ...grpc.CallOption) (*BuildWindowResponse, error)
	UpdateMemory(ctx context.Context, in *UpdateMemoryRequest, opts ...grpc.CallOption) (*UpdateMemoryResponse, error)
	IngestRepo(ctx context.Context, in *IngestRepoRequest, opts ...grpc.CallOption) (*IngestRepoResponse, error)
}

type contextEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewContextEngineClient(cc grpc.ClientConnInterface) ContextEngineClient {
	return &contextEngineClient{cc}
}

func (c *contextEngineClient) BuildWindow(ctx context.Context, in *BuildWindowRequest, opts ...grpc.CallOption) (*BuildWindowResponse, error) {
	out := new(BuildWindowResponse)
	err := c.cc.Invoke(ctx, ContextEngine_BuildWindow_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextEngineClient) UpdateMemory(ctx context.Context, in *UpdateMemoryRequest, opts ...grpc.CallOption) (*UpdateMemoryResponse, error) {
	out := new(UpdateMemoryResponse)
	err := c.cc.Invoke(ctx, ContextEngine_UpdateMemory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextEngineClient) IngestRepo(ctx context.Context, in *IngestRepoRequest, opts ...grpc.CallOption) (*IngestRepoResponse, error) {
	out := new(IngestRepoResponse)
	err := c.cc.Invoke(ctx, ContextEngine_IngestRepo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContextEngineServer is the server API for ContextEngine service.
// All implementations must embed UnimplementedContextEngineServer
// for forward compatibility
type ContextEngineServer interface {
	BuildWindow(context.Context, *BuildWindowRequest) (*BuildWindowResponse, error)
	UpdateMemory(context.Context, *UpdateMemoryRequest) (*UpdateMemoryResponse, error)
	IngestRepo(context.Context, *IngestRepoRequest) (*IngestRepoResponse, error)
	mustEmbedUnimplementedContextEngineServer()
}

// UnimplementedContextEngineServer must be embedded to have forward compatible implementations.
type UnimplementedContextEngineServer struct {
}

func (UnimplementedContextEngineServer) BuildWindow(context.Context, *BuildWindowRequest) (*BuildWindowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuildWindow not implemented")
}
func (UnimplementedContextEngineServer) UpdateMemory(context.Context, *UpdateMemoryRequest) (*UpdateMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMemory not implemented")
}
func (UnimplementedContextEngineServer) IngestRepo(context.Context, *IngestRepoRequest) (*IngestRepoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngestRepo not implemented")
}
func (UnimplementedContextEngineServer) mustEmbedUnimplementedContextEngineServer() {}

// UnsafeContextEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContextEngineServer will
// result in compilation errors.
type UnsafeContextEngineServer interface {
	mustEmbedUnimplementedContextEngineServer()
}

func RegisterContextEngineServer(s grpc.ServiceRegistrar, srv ContextEngineServer) {
	s.RegisterService(&ContextEngine_ServiceDesc, srv)
}

func _ContextEngine_BuildWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildWindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextEngineServer).BuildWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextEngine_BuildWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextEngineServer).BuildWindow(ctx, req.(*BuildWindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextEngine_UpdateMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextEngineServer).UpdateMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextEngine_UpdateMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextEngineServer).UpdateMemory(ctx, req.(*UpdateMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextEngine_IngestRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextEngineServer).IngestRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextEngine_IngestRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextEngineServer).IngestRepo(ctx, req.(*IngestRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContextEngine_ServiceDesc is the grpc.ServiceDesc for ContextEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContextEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coretex.v1.ContextEngine",
	HandlerType: (*ContextEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuildWindow",
			Handler:    _ContextEngine_BuildWindow_Handler,
		},
		{
			MethodName: "UpdateMemory",
			Handler:    _ContextEngine_UpdateMemory_Handler,
		},
		{
			MethodName: "IngestRepo",
			Handler:    _ContextEngine_IngestRepo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "context.proto",
}
