// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: safety.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecisionType int32

const (
	DecisionType_DECISION_TYPE_UNSPECIFIED DecisionType = 0
	DecisionType_DECISION_TYPE_ALLOW       DecisionType = 1
	DecisionType_DECISION_TYPE_DENY        DecisionType = 2
)

// Enum value maps for DecisionType.
var (
	DecisionType_name = map[int32]string{
		0: "DECISION_TYPE_UNSPECIFIED",
		1: "DECISION_TYPE_ALLOW",
		2: "DECISION_TYPE_DENY",
	}
	DecisionType_value = map[string]int32{
		"DECISION_TYPE_UNSPECIFIED": 0,
		"DECISION_TYPE_ALLOW":       1,
		"DECISION_TYPE_DENY":        2,
	}
)

func (x DecisionType) Enum() *DecisionType {
	p := new(DecisionType)
	*p = x
	return p
}

func (x DecisionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DecisionType) Descriptor() protoreflect.EnumDescriptor {
	return file_safety_proto_enumTypes[0].Descriptor()
}

func (DecisionType) Type() protoreflect.EnumType {
	return &file_safety_proto_enumTypes[0]
}

func (x DecisionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DecisionType.Descriptor instead.
func (DecisionType) EnumDescriptor() ([]byte, []int) {
	return file_safety_proto_rawDescGZIP(), []int{0}
}

type PolicyCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId  string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Topic  string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Tenant string `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
}

func (x *PolicyCheckRequest) Reset() {
	*x = PolicyCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_safety_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyCheckRequest) ProtoMessage() {}

func (x *PolicyCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_safety_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyCheckRequest.ProtoReflect.Descriptor instead.
func (*PolicyCheckRequest) Descriptor() ([]byte, []int) {
	return file_safety_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyCheckRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PolicyCheckRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PolicyCheckRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type PolicyCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Decision DecisionType `protobuf:"varint,1,opt,name=decision,proto3,enum=coretex.v1.DecisionType" json:"decision,omitempty"`
	Reason   string       `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *PolicyCheckResponse) Reset() {
	*x = PolicyCheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_safety_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyCheckResponse) ProtoMessage() {}

func (x *PolicyCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_safety_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyCheckResponse.ProtoReflect.Descriptor instead.
func (*PolicyCheckResponse) Descriptor() ([]byte, []int) {
	return file_safety_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyCheckResponse) GetDecision() DecisionType {
	if x != nil {
		return x.Decision
	}
	return DecisionType_DECISION_TYPE_UNSPECIFIED
}

func (x *PolicyCheckResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_safety_proto protoreflect.FileDescriptor

var file_safety_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x61, 0x66, 0x65, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x63, 0x6f, 0x72, 0x74, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x22, 0x59, 0x0a, 0x12, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x22, 0x62, 0x0a, 0x13, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x64,
	0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e,
	0x63, 0x6f, 0x72, 0x74, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2a, 0x5e, 0x0a, 0x0c, 0x44, 0x65, 0x63, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x19, 0x44, 0x45, 0x43, 0x49,
	0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x44, 0x45, 0x43, 0x49, 0x53,
	0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x10, 0x01,
	0x12, 0x16, 0x0a, 0x12, 0x44, 0x45, 0x43, 0x49, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x44, 0x45, 0x4e, 0x59, 0x10, 0x02, 0x32, 0x56, 0x0a, 0x0c, 0x53, 0x61, 0x66, 0x65,
	0x74, 0x79, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x12, 0x46, 0x0a, 0x05, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x72, 0x74, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x63, 0x6f, 0x72, 0x74, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79,
	0x61, 0x72, 0x6f, 0x6e, 0x74, 0x31, 0x31, 0x31, 0x31, 0x2f, 0x63, 0x6f, 0x72, 0x74, 0x65, 0x78,
	0x2d, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_safety_proto_rawDescOnce sync.Once
	file_safety_proto_rawDescData = file_safety_proto_rawDesc
)

func file_safety_proto_rawDescGZIP() []byte {
	file_safety_proto_rawDescOnce.Do(func() {
		file_safety_proto_rawDescData = protoimpl.X.CompressGZIP(file_safety_proto_rawDescData)
	})
	return file_safety_proto_rawDescData
}

var file_safety_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_safety_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_safety_proto_goTypes = []interface{}{
	(DecisionType)(0),           // 0: coretex.v1.DecisionType
	(*PolicyCheckRequest)(nil),  // 1: coretex.v1.PolicyCheckRequest
	(*PolicyCheckResponse)(nil), // 2: coretex.v1.PolicyCheckResponse
}
var file_safety_proto_depIdxs = []int32{
	0, // 0: coretex.v1.PolicyCheckResponse.decision:type_name -> coretex.v1.DecisionType
	1, // 1: coretex.v1.SafetyKernel.Check:input_type -> coretex.v1.PolicyCheckRequest
	2, // 2: coretex.v1.SafetyKernel.Check:output_type -> coretex.v1.PolicyCheckResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_safety_proto_init() }
func file_safety_proto_init() {
	if File_safety_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_safety_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_safety_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyCheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_safety_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_safety_proto_goTypes,
		DependencyIndexes: file_safety_proto_depIdxs,
		EnumInfos:         file_safety_proto_enumTypes,
		MessageInfos:      file_safety_proto_msgTypes,
	}.Build()
	File_safety_proto = out.File
	file_safety_proto_rawDesc = nil
	file_safety_proto_goTypes = nil
	file_safety_proto_depIdxs = nil
}
