import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  gettingStarted: [
    {
      type: 'autogenerated',
      dirName: 'getting-started',
    },
  ],
  concepts: [
    {
      type: 'autogenerated',
      dirName: 'concepts',
    },
  ],
  tutorials: [
    {
      type: 'autogenerated',
      dirName: 'tutorials',
    },
  ],
  apiReference: [
    {
      type: 'autogenerated',
      dirName: 'api-reference',
    },
  ],
  operations: [
    {
      type: 'autogenerated',
      dirName: 'operations',
    },
  ],
  sso: [
    {
      type: 'autogenerated',
      dirName: 'sso',
    },
  ],
};

export default sidebars;
