apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base.yaml
  - nats.yaml
  - redis.yaml
  - ingress.yaml
  - ha.yaml
  - monitoring.yaml
  - networkpolicy.yaml
  - backup.yaml

patches:
  - path: patches/delete-nats-deployment.yaml
  - path: patches/delete-redis-deployment.yaml
  - path: patches/tls-env.yaml
  - path: patches/service-labels.yaml
  - path: patches/pod-anti-affinity.yaml

images:
  - name: cordum-context-engine
    newTag: v0.1.0
  - name: cordum-safety-kernel
    newTag: v0.1.0
  - name: cordum-scheduler
    newTag: v0.1.0
  - name: cordum-api-gateway
    newTag: v0.1.0
  - name: cordum-workflow-engine
    newTag: v0.1.0
  - name: cordum-dashboard
    newTag: v0.1.0

replicas:
  - name: cordum-api-gateway
    count: 2
  - name: cordum-safety-kernel
    count: 2
  - name: cordum-scheduler
    count: 2
