package llmchat

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/gorilla/websocket"
)

func TestChatWSGeneratesSessionIDAndResumesExisting(t *testing.T) {
	runner := &scriptedChatRunner{frames: [][]Frame{{{Type: FrameUser, Text: "hi"}, {Type: FrameFinal, Text: "hello"}}}}
	sessions := newFakeChatSessionStore()
	h := newTestChatHandlers(runner, sessions, true)

	server := httptest.NewServer(http.HandlerFunc(h.HandleChatWS))
	defer server.Close()
	url := "ws" + strings.TrimPrefix(server.URL, "http")
	conn, resp, err := websocket.DefaultDialer.Dial(url, nil)
	if err != nil {
		t.Fatalf("dial new ws: %v resp=%v", err, resp)
	}
	defer func() { _ = conn.Close() }()
	if resp.Header.Get(HeaderChatSessionID) == "" {
		t.Fatalf("upgrade response missing %s", HeaderChatSessionID)
	}
	if err := conn.WriteJSON(chatPostRequest{Message: "hi"}); err != nil {
		t.Fatalf("write: %v", err)
	}
	var first Frame
	if err := conn.ReadJSON(&first); err != nil {
		t.Fatalf("read first frame: %v", err)
	}
	if first.SessionID == "" || first.Type != FrameUser {
		t.Fatalf("first frame=%+v want user with generated session_id", first)
	}
	_ = conn.Close()

	// Resume with the session id generated by the first connection.
	header := http.Header{}
	header.Set(HeaderChatSessionID, first.SessionID)
	var conn2 *websocket.Conn
	for attempt := 0; attempt < 10; attempt++ {
		conn2, _, err = websocket.DefaultDialer.Dial(url, header)
		if err == nil {
			break
		}
		time.Sleep(20 * time.Millisecond)
	}
	if err != nil {
		t.Fatalf("dial resume ws after close: %v", err)
	}
	defer func() { _ = conn2.Close() }()
	if err := conn2.WriteJSON(chatPostRequest{Message: "again"}); err != nil {
		t.Fatalf("write resume: %v", err)
	}
	var resumed Frame
	if err := conn2.ReadJSON(&resumed); err != nil {
		t.Fatalf("read resumed: %v", err)
	}
	if resumed.SessionID != first.SessionID {
		t.Fatalf("resumed SessionID=%q want %q", resumed.SessionID, first.SessionID)
	}
	if sessions.createdN != 1 {
		t.Fatalf("createdN=%d want one session reused", sessions.createdN)
	}
}

func TestChatWSOversizeMessageClosesWithErrorFrame(t *testing.T) {
	h := newTestChatHandlers(&scriptedChatRunner{}, newFakeChatSessionStore(), true)
	server := httptest.NewServer(http.HandlerFunc(h.HandleChatWS))
	defer server.Close()
	conn, _, err := websocket.DefaultDialer.Dial("ws"+strings.TrimPrefix(server.URL, "http"), nil)
	if err != nil {
		t.Fatalf("dial: %v", err)
	}
	defer func() { _ = conn.Close() }()

	oversized := strings.Repeat("x", maxWSMessageBytes+1)
	if err := conn.WriteMessage(websocket.TextMessage, []byte(`{"message":"`+oversized+`"}`)); err != nil {
		t.Fatalf("write oversized: %v", err)
	}
	var frame Frame
	if err := conn.ReadJSON(&frame); err != nil {
		t.Fatalf("read error frame: %v", err)
	}
	if frame.Type != FrameError || frame.ErrorCode != "message_too_large" {
		t.Fatalf("frame=%+v want message_too_large error", frame)
	}
}

func TestApprovalResumeResolvedAndRejectedOverFakeBus(t *testing.T) {
	bus := newFakeApprovalBus()
	runner := &scriptedChatRunner{
		frames: [][]Frame{
			{{Type: FrameApprovalRequired, ApprovalID: "appr-7"}},
			{{Type: FrameApprovalRequired, ApprovalID: "appr-8"}},
		},
		resumeFrames: [][]Frame{
			{{Type: FrameToolResult, ToolResult: `{"ok":true}`}, {Type: FrameFinal, Text: "approved done"}},
			{{Type: FrameToolResult, ToolResult: "denied by human reviewer", IsError: true}, {Type: FrameFinal, Text: "The reviewer denied it."}},
		},
	}
	sessions := newFakeChatSessionStore()
	h := newTestChatHandlers(runner, sessions, true)
	h.approvals = NewApprovalResumer(ApprovalResumerConfig{Bus: bus, Runner: runner})
	defer func() { _ = h.approvals.Close() }()

	server := httptest.NewServer(http.HandlerFunc(h.HandleChatWS))
	defer server.Close()
	conn, _, err := websocket.DefaultDialer.Dial("ws"+strings.TrimPrefix(server.URL, "http"), nil)
	if err != nil {
		t.Fatalf("dial: %v", err)
	}
	defer func() { _ = conn.Close() }()
	if err := conn.WriteJSON(chatPostRequest{Message: "mutate"}); err != nil {
		t.Fatalf("write: %v", err)
	}
	var approval Frame
	if err := conn.ReadJSON(&approval); err != nil {
		t.Fatalf("read approval: %v", err)
	}
	if approval.Type != FrameApprovalRequired || approval.ApprovalID != "appr-7" {
		t.Fatalf("approval frame=%+v", approval)
	}
	bus.Publish(ApprovalEvent{ApprovalID: "appr-7", AgentID: "chat-assistant", SessionID: approval.SessionID, Status: ApprovalStatusResolved})
	got := readWSFramesUntilFinal(t, conn, 2*time.Second)
	if got[0].Type != FrameToolResult || got[len(got)-1].Text != "approved done" {
		t.Fatalf("resolved frames=%+v", got)
	}

	if err := conn.WriteJSON(chatPostRequest{Message: "mutate again"}); err != nil {
		t.Fatalf("write second message: %v", err)
	}
	var approval2 Frame
	if err := conn.ReadJSON(&approval2); err != nil {
		t.Fatalf("read second approval: %v", err)
	}
	if approval2.Type != FrameApprovalRequired || approval2.ApprovalID != "appr-8" {
		t.Fatalf("approval2 frame=%+v", approval2)
	}
	bus.Publish(ApprovalEvent{ApprovalID: "appr-8", AgentID: "chat-assistant", SessionID: approval.SessionID, Status: ApprovalStatusRejected})
	got = readWSFramesUntilFinal(t, conn, 2*time.Second)
	if got[0].Type != FrameToolResult || !got[0].IsError || got[0].ToolResult != "denied by human reviewer" {
		raw, _ := json.Marshal(got)
		t.Fatalf("rejected frames=%s want synthetic error tool_result first", raw)
	}
	if got[len(got)-1].Type != FrameFinal || got[len(got)-1].Text == "denied by human reviewer" {
		t.Fatalf("rejected final=%+v want LLM-narrated continuation", got[len(got)-1])
	}
}

func readWSFramesUntilFinal(t *testing.T, conn *websocket.Conn, timeout time.Duration) []Frame {
	t.Helper()
	if err := conn.SetReadDeadline(time.Now().Add(timeout)); err != nil {
		t.Fatalf("set read deadline: %v", err)
	}
	var frames []Frame
	for {
		var f Frame
		if err := conn.ReadJSON(&f); err != nil {
			t.Fatalf("read frame before final: %v; frames=%+v", err, frames)
		}
		frames = append(frames, f)
		if f.Type == FrameFinal {
			return frames
		}
	}
}
