package llmchat

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/gorilla/websocket"

	gatewayauth "github.com/cordum/cordum/core/controlplane/gateway/auth"
)

func TestChatWSGeneratesSessionIDAndResumesExisting(t *testing.T) {
	runner := &scriptedChatRunner{frames: [][]Frame{{{Type: FrameUser, Text: "hi"}, {Type: FrameFinal, Text: "hello"}}}}
	sessions := newFakeChatSessionStore()
	h := newTestChatHandlers(runner, sessions, true)

	server := httptest.NewServer(http.HandlerFunc(h.HandleChatWS))
	defer server.Close()
	url := "ws" + strings.TrimPrefix(server.URL, "http")
	conn, resp, err := websocket.DefaultDialer.Dial(url, nil)
	if err != nil {
		t.Fatalf("dial new ws: %v resp=%v", err, resp)
	}
	defer func() { _ = conn.Close() }()
	if resp.Header.Get(HeaderChatSessionID) == "" {
		t.Fatalf("upgrade response missing %s", HeaderChatSessionID)
	}
	if err := conn.WriteJSON(chatPostRequest{Message: "hi"}); err != nil {
		t.Fatalf("write: %v", err)
	}
	var first Frame
	if err := conn.ReadJSON(&first); err != nil {
		t.Fatalf("read first frame: %v", err)
	}
	if first.SessionID == "" || first.Type != FrameUser {
		t.Fatalf("first frame=%+v want user with generated session_id", first)
	}
	_ = conn.Close()

	// Resume with the session id generated by the first connection.
	header := http.Header{}
	header.Set(HeaderChatSessionID, first.SessionID)
	var conn2 *websocket.Conn
	for attempt := 0; attempt < 10; attempt++ {
		conn2, _, err = websocket.DefaultDialer.Dial(url, header)
		if err == nil {
			break
		}
		time.Sleep(20 * time.Millisecond)
	}
	if err != nil {
		t.Fatalf("dial resume ws after close: %v", err)
	}
	defer func() { _ = conn2.Close() }()
	if err := conn2.WriteJSON(chatPostRequest{Message: "again"}); err != nil {
		t.Fatalf("write resume: %v", err)
	}
	var resumed Frame
	if err := conn2.ReadJSON(&resumed); err != nil {
		t.Fatalf("read resumed: %v", err)
	}
	if resumed.SessionID != first.SessionID {
		t.Fatalf("resumed SessionID=%q want %q", resumed.SessionID, first.SessionID)
	}
	if sessions.createdN != 1 {
		t.Fatalf("createdN=%d want one session reused", sessions.createdN)
	}
}

func TestChatWSBrowserQuerySessionTextPayloadAndSubprotocol(t *testing.T) {
	runner := &scriptedChatRunner{frames: [][]Frame{{{Type: FrameAssistantDelta, Text: "hello"}, {Type: FrameFinal, Text: "hello"}}}}
	sessions := newFakeChatSessionStore()
	h := newTestChatHandlers(runner, sessions, true)

	server := httptest.NewServer(http.HandlerFunc(h.HandleChatWS))
	defer server.Close()
	url := "ws" + strings.TrimPrefix(server.URL, "http") + "?session_id=browser-session-1"
	dialer := websocket.Dialer{Subprotocols: []string{gatewayauth.WSAuthSubprotocol, "token-placeholder"}}
	conn, resp, err := dialer.Dial(url, nil)
	if err != nil {
		t.Fatalf("dial browser-shaped ws: %v resp=%v", err, resp)
	}
	defer func() { _ = conn.Close() }()
	if got := resp.Header.Get("Sec-WebSocket-Protocol"); got != gatewayauth.WSAuthSubprotocol {
		t.Fatalf("Sec-WebSocket-Protocol=%q want %q", got, gatewayauth.WSAuthSubprotocol)
	}
	if got := resp.Header.Get(HeaderChatSessionID); got != "browser-session-1" {
		t.Fatalf("%s=%q want browser-session-1", HeaderChatSessionID, got)
	}
	if err := conn.WriteMessage(websocket.TextMessage, []byte(`{"type":"user","text":"hi from dashboard"}`)); err != nil {
		t.Fatalf("write browser text payload: %v", err)
	}
	var first Frame
	if err := conn.ReadJSON(&first); err != nil {
		t.Fatalf("read first response frame: %v", err)
	}
	if first.SessionID != "browser-session-1" {
		t.Fatalf("first SessionID=%q want browser-session-1", first.SessionID)
	}
	turns, _ := runner.snapshot()
	if len(turns) != 1 || turns[0].UserMessage != "hi from dashboard" {
		t.Fatalf("turns=%+v want text alias routed to one agent turn", turns)
	}
	if sessions.createdN != 1 {
		t.Fatalf("createdN=%d want browser query session created once", sessions.createdN)
	}
}

func TestChatWSOversizeMessageClosesWithErrorFrame(t *testing.T) {
	h := newTestChatHandlers(&scriptedChatRunner{}, newFakeChatSessionStore(), true)
	server := httptest.NewServer(http.HandlerFunc(h.HandleChatWS))
	defer server.Close()
	conn, _, err := websocket.DefaultDialer.Dial("ws"+strings.TrimPrefix(server.URL, "http"), nil)
	if err != nil {
		t.Fatalf("dial: %v", err)
	}
	defer func() { _ = conn.Close() }()

	oversized := strings.Repeat("x", maxWSMessageBytes+1)
	if err := conn.WriteMessage(websocket.TextMessage, []byte(`{"message":"`+oversized+`"}`)); err != nil {
		t.Fatalf("write oversized: %v", err)
	}
	var frame Frame
	if err := conn.ReadJSON(&frame); err != nil {
		t.Fatalf("read error frame: %v", err)
	}
	if frame.Type != FrameError || frame.ErrorCode != "message_too_large" {
		t.Fatalf("frame=%+v want message_too_large error", frame)
	}
}
