// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: context.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContextMode int32

const (
	ContextMode_CONTEXT_MODE_UNSPECIFIED ContextMode = 0
	ContextMode_CONTEXT_MODE_RAW         ContextMode = 1
	ContextMode_CONTEXT_MODE_CHAT        ContextMode = 2
	ContextMode_CONTEXT_MODE_RAG         ContextMode = 3
)

// Enum value maps for ContextMode.
var (
	ContextMode_name = map[int32]string{
		0: "CONTEXT_MODE_UNSPECIFIED",
		1: "CONTEXT_MODE_RAW",
		2: "CONTEXT_MODE_CHAT",
		3: "CONTEXT_MODE_RAG",
	}
	ContextMode_value = map[string]int32{
		"CONTEXT_MODE_UNSPECIFIED": 0,
		"CONTEXT_MODE_RAW":         1,
		"CONTEXT_MODE_CHAT":        2,
		"CONTEXT_MODE_RAG":         3,
	}
)

func (x ContextMode) Enum() *ContextMode {
	p := new(ContextMode)
	*p = x
	return p
}

func (x ContextMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContextMode) Descriptor() protoreflect.EnumDescriptor {
	return file_context_proto_enumTypes[0].Descriptor()
}

func (ContextMode) Type() protoreflect.EnumType {
	return &file_context_proto_enumTypes[0]
}

func (x ContextMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContextMode.Descriptor instead.
func (ContextMode) EnumDescriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{0}
}

// MemoryWriteKind classifies the KIND of state a memory write touches.
// Raw and chat are backward-compatible — they stay on the legacy
// context-engine path. Writes that mutate shared policy / trust /
// directive state are guarded by core/governance/evaluator and the
// service-level provenance check; they require a verified writer and
// non-empty provenance_ref or the write fails closed.
type MemoryWriteKind int32

const (
	MemoryWriteKind_MEMORY_WRITE_KIND_UNSPECIFIED         MemoryWriteKind = 0
	MemoryWriteKind_MEMORY_WRITE_KIND_RAW                 MemoryWriteKind = 1
	MemoryWriteKind_MEMORY_WRITE_KIND_CHAT                MemoryWriteKind = 2
	MemoryWriteKind_MEMORY_WRITE_KIND_SHARED_POLICY_STATE MemoryWriteKind = 3
	MemoryWriteKind_MEMORY_WRITE_KIND_SHARED_TRUST_STATE  MemoryWriteKind = 4
	MemoryWriteKind_MEMORY_WRITE_KIND_SHARED_DIRECTIVE    MemoryWriteKind = 5
)

// Enum value maps for MemoryWriteKind.
var (
	MemoryWriteKind_name = map[int32]string{
		0: "MEMORY_WRITE_KIND_UNSPECIFIED",
		1: "MEMORY_WRITE_KIND_RAW",
		2: "MEMORY_WRITE_KIND_CHAT",
		3: "MEMORY_WRITE_KIND_SHARED_POLICY_STATE",
		4: "MEMORY_WRITE_KIND_SHARED_TRUST_STATE",
		5: "MEMORY_WRITE_KIND_SHARED_DIRECTIVE",
	}
	MemoryWriteKind_value = map[string]int32{
		"MEMORY_WRITE_KIND_UNSPECIFIED":         0,
		"MEMORY_WRITE_KIND_RAW":                 1,
		"MEMORY_WRITE_KIND_CHAT":                2,
		"MEMORY_WRITE_KIND_SHARED_POLICY_STATE": 3,
		"MEMORY_WRITE_KIND_SHARED_TRUST_STATE":  4,
		"MEMORY_WRITE_KIND_SHARED_DIRECTIVE":    5,
	}
)

func (x MemoryWriteKind) Enum() *MemoryWriteKind {
	p := new(MemoryWriteKind)
	*p = x
	return p
}

func (x MemoryWriteKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemoryWriteKind) Descriptor() protoreflect.EnumDescriptor {
	return file_context_proto_enumTypes[1].Descriptor()
}

func (MemoryWriteKind) Type() protoreflect.EnumType {
	return &file_context_proto_enumTypes[1]
}

func (x MemoryWriteKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemoryWriteKind.Descriptor instead.
func (MemoryWriteKind) EnumDescriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{1}
}

type ModelMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelMessage) Reset() {
	*x = ModelMessage{}
	mi := &file_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelMessage) ProtoMessage() {}

func (x *ModelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelMessage.ProtoReflect.Descriptor instead.
func (*ModelMessage) Descriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{0}
}

func (x *ModelMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ModelMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type BuildWindowRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MemoryId        string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	Mode            ContextMode            `protobuf:"varint,2,opt,name=mode,proto3,enum=cordum.v1.ContextMode" json:"mode,omitempty"`
	Model           string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	LogicalPayload  []byte                 `protobuf:"bytes,4,opt,name=logical_payload,json=logicalPayload,proto3" json:"logical_payload,omitempty"`
	MaxInputTokens  int32                  `protobuf:"varint,5,opt,name=max_input_tokens,json=maxInputTokens,proto3" json:"max_input_tokens,omitempty"`
	MaxOutputTokens int32                  `protobuf:"varint,6,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BuildWindowRequest) Reset() {
	*x = BuildWindowRequest{}
	mi := &file_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildWindowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildWindowRequest) ProtoMessage() {}

func (x *BuildWindowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildWindowRequest.ProtoReflect.Descriptor instead.
func (*BuildWindowRequest) Descriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{1}
}

func (x *BuildWindowRequest) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *BuildWindowRequest) GetMode() ContextMode {
	if x != nil {
		return x.Mode
	}
	return ContextMode_CONTEXT_MODE_UNSPECIFIED
}

func (x *BuildWindowRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *BuildWindowRequest) GetLogicalPayload() []byte {
	if x != nil {
		return x.LogicalPayload
	}
	return nil
}

func (x *BuildWindowRequest) GetMaxInputTokens() int32 {
	if x != nil {
		return x.MaxInputTokens
	}
	return 0
}

func (x *BuildWindowRequest) GetMaxOutputTokens() int32 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

type BuildWindowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ModelMessage        `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	InputTokens   int32                  `protobuf:"varint,2,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,3,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildWindowResponse) Reset() {
	*x = BuildWindowResponse{}
	mi := &file_context_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildWindowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildWindowResponse) ProtoMessage() {}

func (x *BuildWindowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_context_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildWindowResponse.ProtoReflect.Descriptor instead.
func (*BuildWindowResponse) Descriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{2}
}

func (x *BuildWindowResponse) GetMessages() []*ModelMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *BuildWindowResponse) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *BuildWindowResponse) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

type UpdateMemoryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MemoryId       string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	LogicalPayload []byte                 `protobuf:"bytes,2,opt,name=logical_payload,json=logicalPayload,proto3" json:"logical_payload,omitempty"`
	ModelResponse  []byte                 `protobuf:"bytes,3,opt,name=model_response,json=modelResponse,proto3" json:"model_response,omitempty"`
	Mode           ContextMode            `protobuf:"varint,4,opt,name=mode,proto3,enum=cordum.v1.ContextMode" json:"mode,omitempty"`
	// Server-owned multi-agent governance fields, populated by the
	// context-engine caller AFTER authenticating + verifying the writer
	// and the target. These MUST NOT be set by external clients; the
	// gateway / scheduler set them after lookup against the auth store
	// and the delegation/approval stores. The service enforces a
	// fail-closed check when write_kind mutates policy/trust/directive
	// state and writer_agent_id or provenance_ref is empty.
	TenantId            string          `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WriterAgentId       string          `protobuf:"bytes,6,opt,name=writer_agent_id,json=writerAgentId,proto3" json:"writer_agent_id,omitempty"`
	TargetAgentId       string          `protobuf:"bytes,7,opt,name=target_agent_id,json=targetAgentId,proto3" json:"target_agent_id,omitempty"`
	ProvenanceRef       string          `protobuf:"bytes,8,opt,name=provenance_ref,json=provenanceRef,proto3" json:"provenance_ref,omitempty"`
	ProvenanceVerified  bool            `protobuf:"varint,9,opt,name=provenance_verified,json=provenanceVerified,proto3" json:"provenance_verified,omitempty"`
	WriteKind           MemoryWriteKind `protobuf:"varint,10,opt,name=write_kind,json=writeKind,proto3,enum=cordum.v1.MemoryWriteKind" json:"write_kind,omitempty"`
	PolicyStateMutation bool            `protobuf:"varint,11,opt,name=policy_state_mutation,json=policyStateMutation,proto3" json:"policy_state_mutation,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateMemoryRequest) Reset() {
	*x = UpdateMemoryRequest{}
	mi := &file_context_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemoryRequest) ProtoMessage() {}

func (x *UpdateMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_context_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemoryRequest) Descriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMemoryRequest) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *UpdateMemoryRequest) GetLogicalPayload() []byte {
	if x != nil {
		return x.LogicalPayload
	}
	return nil
}

func (x *UpdateMemoryRequest) GetModelResponse() []byte {
	if x != nil {
		return x.ModelResponse
	}
	return nil
}

func (x *UpdateMemoryRequest) GetMode() ContextMode {
	if x != nil {
		return x.Mode
	}
	return ContextMode_CONTEXT_MODE_UNSPECIFIED
}

func (x *UpdateMemoryRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateMemoryRequest) GetWriterAgentId() string {
	if x != nil {
		return x.WriterAgentId
	}
	return ""
}

func (x *UpdateMemoryRequest) GetTargetAgentId() string {
	if x != nil {
		return x.TargetAgentId
	}
	return ""
}

func (x *UpdateMemoryRequest) GetProvenanceRef() string {
	if x != nil {
		return x.ProvenanceRef
	}
	return ""
}

func (x *UpdateMemoryRequest) GetProvenanceVerified() bool {
	if x != nil {
		return x.ProvenanceVerified
	}
	return false
}

func (x *UpdateMemoryRequest) GetWriteKind() MemoryWriteKind {
	if x != nil {
		return x.WriteKind
	}
	return MemoryWriteKind_MEMORY_WRITE_KIND_UNSPECIFIED
}

func (x *UpdateMemoryRequest) GetPolicyStateMutation() bool {
	if x != nil {
		return x.PolicyStateMutation
	}
	return false
}

type UpdateMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemoryResponse) Reset() {
	*x = UpdateMemoryResponse{}
	mi := &file_context_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemoryResponse) ProtoMessage() {}

func (x *UpdateMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_context_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateMemoryResponse) Descriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{4}
}

var File_context_proto protoreflect.FileDescriptor

const file_context_proto_rawDesc = "" +
	"\n" +
	"\rcontext.proto\x12\tcordum.v1\"<\n" +
	"\fModelMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xf2\x01\n" +
	"\x12BuildWindowRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12*\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x16.cordum.v1.ContextModeR\x04mode\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12'\n" +
	"\x0flogical_payload\x18\x04 \x01(\fR\x0elogicalPayload\x12(\n" +
	"\x10max_input_tokens\x18\x05 \x01(\x05R\x0emaxInputTokens\x12*\n" +
	"\x11max_output_tokens\x18\x06 \x01(\x05R\x0fmaxOutputTokens\"\x92\x01\n" +
	"\x13BuildWindowResponse\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.cordum.v1.ModelMessageR\bmessages\x12!\n" +
	"\finput_tokens\x18\x02 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x03 \x01(\x05R\foutputTokens\"\xe2\x03\n" +
	"\x13UpdateMemoryRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12'\n" +
	"\x0flogical_payload\x18\x02 \x01(\fR\x0elogicalPayload\x12%\n" +
	"\x0emodel_response\x18\x03 \x01(\fR\rmodelResponse\x12*\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x16.cordum.v1.ContextModeR\x04mode\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12&\n" +
	"\x0fwriter_agent_id\x18\x06 \x01(\tR\rwriterAgentId\x12&\n" +
	"\x0ftarget_agent_id\x18\a \x01(\tR\rtargetAgentId\x12%\n" +
	"\x0eprovenance_ref\x18\b \x01(\tR\rprovenanceRef\x12/\n" +
	"\x13provenance_verified\x18\t \x01(\bR\x12provenanceVerified\x129\n" +
	"\n" +
	"write_kind\x18\n" +
	" \x01(\x0e2\x1a.cordum.v1.MemoryWriteKindR\twriteKind\x122\n" +
	"\x15policy_state_mutation\x18\v \x01(\bR\x13policyStateMutation\"\x16\n" +
	"\x14UpdateMemoryResponse*n\n" +
	"\vContextMode\x12\x1c\n" +
	"\x18CONTEXT_MODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CONTEXT_MODE_RAW\x10\x01\x12\x15\n" +
	"\x11CONTEXT_MODE_CHAT\x10\x02\x12\x14\n" +
	"\x10CONTEXT_MODE_RAG\x10\x03*\xe8\x01\n" +
	"\x0fMemoryWriteKind\x12!\n" +
	"\x1dMEMORY_WRITE_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MEMORY_WRITE_KIND_RAW\x10\x01\x12\x1a\n" +
	"\x16MEMORY_WRITE_KIND_CHAT\x10\x02\x12)\n" +
	"%MEMORY_WRITE_KIND_SHARED_POLICY_STATE\x10\x03\x12(\n" +
	"$MEMORY_WRITE_KIND_SHARED_TRUST_STATE\x10\x04\x12&\n" +
	"\"MEMORY_WRITE_KIND_SHARED_DIRECTIVE\x10\x052\xae\x01\n" +
	"\rContextEngine\x12L\n" +
	"\vBuildWindow\x12\x1d.cordum.v1.BuildWindowRequest\x1a\x1e.cordum.v1.BuildWindowResponse\x12O\n" +
	"\fUpdateMemory\x12\x1e.cordum.v1.UpdateMemoryRequest\x1a\x1f.cordum.v1.UpdateMemoryResponseB.Z,github.com/cordum/cordum/core/protocol/pb/v1b\x06proto3"

var (
	file_context_proto_rawDescOnce sync.Once
	file_context_proto_rawDescData []byte
)

func file_context_proto_rawDescGZIP() []byte {
	file_context_proto_rawDescOnce.Do(func() {
		file_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_context_proto_rawDesc), len(file_context_proto_rawDesc)))
	})
	return file_context_proto_rawDescData
}

var file_context_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_context_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_context_proto_goTypes = []any{
	(ContextMode)(0),             // 0: cordum.v1.ContextMode
	(MemoryWriteKind)(0),         // 1: cordum.v1.MemoryWriteKind
	(*ModelMessage)(nil),         // 2: cordum.v1.ModelMessage
	(*BuildWindowRequest)(nil),   // 3: cordum.v1.BuildWindowRequest
	(*BuildWindowResponse)(nil),  // 4: cordum.v1.BuildWindowResponse
	(*UpdateMemoryRequest)(nil),  // 5: cordum.v1.UpdateMemoryRequest
	(*UpdateMemoryResponse)(nil), // 6: cordum.v1.UpdateMemoryResponse
}
var file_context_proto_depIdxs = []int32{
	0, // 0: cordum.v1.BuildWindowRequest.mode:type_name -> cordum.v1.ContextMode
	2, // 1: cordum.v1.BuildWindowResponse.messages:type_name -> cordum.v1.ModelMessage
	0, // 2: cordum.v1.UpdateMemoryRequest.mode:type_name -> cordum.v1.ContextMode
	1, // 3: cordum.v1.UpdateMemoryRequest.write_kind:type_name -> cordum.v1.MemoryWriteKind
	3, // 4: cordum.v1.ContextEngine.BuildWindow:input_type -> cordum.v1.BuildWindowRequest
	5, // 5: cordum.v1.ContextEngine.UpdateMemory:input_type -> cordum.v1.UpdateMemoryRequest
	4, // 6: cordum.v1.ContextEngine.BuildWindow:output_type -> cordum.v1.BuildWindowResponse
	6, // 7: cordum.v1.ContextEngine.UpdateMemory:output_type -> cordum.v1.UpdateMemoryResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_context_proto_init() }
func file_context_proto_init() {
	if File_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_context_proto_rawDesc), len(file_context_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_context_proto_goTypes,
		DependencyIndexes: file_context_proto_depIdxs,
		EnumInfos:         file_context_proto_enumTypes,
		MessageInfos:      file_context_proto_msgTypes,
	}.Build()
	File_context_proto = out.File
	file_context_proto_goTypes = nil
	file_context_proto_depIdxs = nil
}
