// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: output_policy.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OutputPolicyService_CheckOutput_FullMethodName = "/cordum.v1.OutputPolicyService/CheckOutput"
)

// OutputPolicyServiceClient is the client API for OutputPolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OutputPolicyService evaluates job outputs in two phases:
// 1) fast synchronous metadata checks on the scheduler hot path
// 2) deeper asynchronous content scanning on dereferenced output payloads
type OutputPolicyServiceClient interface {
	CheckOutput(ctx context.Context, in *OutputCheckRequest, opts ...grpc.CallOption) (*OutputCheckResponse, error)
}

type outputPolicyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOutputPolicyServiceClient(cc grpc.ClientConnInterface) OutputPolicyServiceClient {
	return &outputPolicyServiceClient{cc}
}

func (c *outputPolicyServiceClient) CheckOutput(ctx context.Context, in *OutputCheckRequest, opts ...grpc.CallOption) (*OutputCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutputCheckResponse)
	err := c.cc.Invoke(ctx, OutputPolicyService_CheckOutput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OutputPolicyServiceServer is the server API for OutputPolicyService service.
// All implementations must embed UnimplementedOutputPolicyServiceServer
// for forward compatibility.
//
// OutputPolicyService evaluates job outputs in two phases:
// 1) fast synchronous metadata checks on the scheduler hot path
// 2) deeper asynchronous content scanning on dereferenced output payloads
type OutputPolicyServiceServer interface {
	CheckOutput(context.Context, *OutputCheckRequest) (*OutputCheckResponse, error)
	mustEmbedUnimplementedOutputPolicyServiceServer()
}

// UnimplementedOutputPolicyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOutputPolicyServiceServer struct{}

func (UnimplementedOutputPolicyServiceServer) CheckOutput(context.Context, *OutputCheckRequest) (*OutputCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckOutput not implemented")
}
func (UnimplementedOutputPolicyServiceServer) mustEmbedUnimplementedOutputPolicyServiceServer() {}
func (UnimplementedOutputPolicyServiceServer) testEmbeddedByValue()                             {}

// UnsafeOutputPolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OutputPolicyServiceServer will
// result in compilation errors.
type UnsafeOutputPolicyServiceServer interface {
	mustEmbedUnimplementedOutputPolicyServiceServer()
}

func RegisterOutputPolicyServiceServer(s grpc.ServiceRegistrar, srv OutputPolicyServiceServer) {
	// If the following call panics, it indicates UnimplementedOutputPolicyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OutputPolicyService_ServiceDesc, srv)
}

func _OutputPolicyService_CheckOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutputCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutputPolicyServiceServer).CheckOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutputPolicyService_CheckOutput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutputPolicyServiceServer).CheckOutput(ctx, req.(*OutputCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OutputPolicyService_ServiceDesc is the grpc.ServiceDesc for OutputPolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OutputPolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cordum.v1.OutputPolicyService",
	HandlerType: (*OutputPolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckOutput",
			Handler:    _OutputPolicyService_CheckOutput_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "output_policy.proto",
}
