// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: output_policy.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutputDecision int32

const (
	OutputDecision_OUTPUT_DECISION_ALLOW      OutputDecision = 0
	OutputDecision_OUTPUT_DECISION_QUARANTINE OutputDecision = 1
	OutputDecision_OUTPUT_DECISION_REDACT     OutputDecision = 2
)

// Enum value maps for OutputDecision.
var (
	OutputDecision_name = map[int32]string{
		0: "OUTPUT_DECISION_ALLOW",
		1: "OUTPUT_DECISION_QUARANTINE",
		2: "OUTPUT_DECISION_REDACT",
	}
	OutputDecision_value = map[string]int32{
		"OUTPUT_DECISION_ALLOW":      0,
		"OUTPUT_DECISION_QUARANTINE": 1,
		"OUTPUT_DECISION_REDACT":     2,
	}
)

func (x OutputDecision) Enum() *OutputDecision {
	p := new(OutputDecision)
	*p = x
	return p
}

func (x OutputDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_output_policy_proto_enumTypes[0].Descriptor()
}

func (OutputDecision) Type() protoreflect.EnumType {
	return &file_output_policy_proto_enumTypes[0]
}

func (x OutputDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputDecision.Descriptor instead.
func (OutputDecision) EnumDescriptor() ([]byte, []int) {
	return file_output_policy_proto_rawDescGZIP(), []int{0}
}

type OutputCheckRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Topic           string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Tenant          string                 `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResultPtr       string                 `protobuf:"bytes,5,opt,name=result_ptr,json=resultPtr,proto3" json:"result_ptr,omitempty"`
	ArtifactPtrs    []string               `protobuf:"bytes,6,rep,name=artifact_ptrs,json=artifactPtrs,proto3" json:"artifact_ptrs,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode       string                 `protobuf:"bytes,8,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	WorkerId        string                 `protobuf:"bytes,9,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ExecutionMs     int64                  `protobuf:"varint,10,opt,name=execution_ms,json=executionMs,proto3" json:"execution_ms,omitempty"`
	OutputSizeBytes int64                  `protobuf:"varint,11,opt,name=output_size_bytes,json=outputSizeBytes,proto3" json:"output_size_bytes,omitempty"`
	ContentHash     string                 `protobuf:"bytes,12,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	WorkflowId      string                 `protobuf:"bytes,13,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	StepId          string                 `protobuf:"bytes,14,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	OutputContent   []byte                 `protobuf:"bytes,15,opt,name=output_content,json=outputContent,proto3" json:"output_content,omitempty"`
	Capabilities    []string               `protobuf:"bytes,16,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	RiskTags        []string               `protobuf:"bytes,17,rep,name=risk_tags,json=riskTags,proto3" json:"risk_tags,omitempty"`
	PrincipalId     string                 `protobuf:"bytes,18,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	PackId          string                 `protobuf:"bytes,19,opt,name=pack_id,json=packId,proto3" json:"pack_id,omitempty"`
	ContentType     string                 `protobuf:"bytes,20,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	OriginalLabels  map[string]string      `protobuf:"bytes,21,rep,name=original_labels,json=originalLabels,proto3" json:"original_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OutputCheckRequest) Reset() {
	*x = OutputCheckRequest{}
	mi := &file_output_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputCheckRequest) ProtoMessage() {}

func (x *OutputCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_output_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputCheckRequest.ProtoReflect.Descriptor instead.
func (*OutputCheckRequest) Descriptor() ([]byte, []int) {
	return file_output_policy_proto_rawDescGZIP(), []int{0}
}

func (x *OutputCheckRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *OutputCheckRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *OutputCheckRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *OutputCheckRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *OutputCheckRequest) GetResultPtr() string {
	if x != nil {
		return x.ResultPtr
	}
	return ""
}

func (x *OutputCheckRequest) GetArtifactPtrs() []string {
	if x != nil {
		return x.ArtifactPtrs
	}
	return nil
}

func (x *OutputCheckRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *OutputCheckRequest) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *OutputCheckRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *OutputCheckRequest) GetExecutionMs() int64 {
	if x != nil {
		return x.ExecutionMs
	}
	return 0
}

func (x *OutputCheckRequest) GetOutputSizeBytes() int64 {
	if x != nil {
		return x.OutputSizeBytes
	}
	return 0
}

func (x *OutputCheckRequest) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *OutputCheckRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *OutputCheckRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *OutputCheckRequest) GetOutputContent() []byte {
	if x != nil {
		return x.OutputContent
	}
	return nil
}

func (x *OutputCheckRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *OutputCheckRequest) GetRiskTags() []string {
	if x != nil {
		return x.RiskTags
	}
	return nil
}

func (x *OutputCheckRequest) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *OutputCheckRequest) GetPackId() string {
	if x != nil {
		return x.PackId
	}
	return ""
}

func (x *OutputCheckRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *OutputCheckRequest) GetOriginalLabels() map[string]string {
	if x != nil {
		return x.OriginalLabels
	}
	return nil
}

type OutputCheckResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Decision       OutputDecision         `protobuf:"varint,1,opt,name=decision,proto3,enum=cordum.v1.OutputDecision" json:"decision,omitempty"`
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	RuleId         string                 `protobuf:"bytes,3,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	PolicySnapshot string                 `protobuf:"bytes,4,opt,name=policy_snapshot,json=policySnapshot,proto3" json:"policy_snapshot,omitempty"`
	Findings       []*OutputFinding       `protobuf:"bytes,5,rep,name=findings,proto3" json:"findings,omitempty"`
	RedactedPtr    string                 `protobuf:"bytes,6,opt,name=redacted_ptr,json=redactedPtr,proto3" json:"redacted_ptr,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OutputCheckResponse) Reset() {
	*x = OutputCheckResponse{}
	mi := &file_output_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputCheckResponse) ProtoMessage() {}

func (x *OutputCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_output_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputCheckResponse.ProtoReflect.Descriptor instead.
func (*OutputCheckResponse) Descriptor() ([]byte, []int) {
	return file_output_policy_proto_rawDescGZIP(), []int{1}
}

func (x *OutputCheckResponse) GetDecision() OutputDecision {
	if x != nil {
		return x.Decision
	}
	return OutputDecision_OUTPUT_DECISION_ALLOW
}

func (x *OutputCheckResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OutputCheckResponse) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *OutputCheckResponse) GetPolicySnapshot() string {
	if x != nil {
		return x.PolicySnapshot
	}
	return ""
}

func (x *OutputCheckResponse) GetFindings() []*OutputFinding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *OutputCheckResponse) GetRedactedPtr() string {
	if x != nil {
		return x.RedactedPtr
	}
	return ""
}

type OutputFinding struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Severity       string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Detail         string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Offset         int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Length         int64                  `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty"`
	Scanner        string                 `protobuf:"bytes,6,opt,name=scanner,proto3" json:"scanner,omitempty"`
	Confidence     float32                `protobuf:"fixed32,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	MatchedPattern string                 `protobuf:"bytes,8,opt,name=matched_pattern,json=matchedPattern,proto3" json:"matched_pattern,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OutputFinding) Reset() {
	*x = OutputFinding{}
	mi := &file_output_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputFinding) ProtoMessage() {}

func (x *OutputFinding) ProtoReflect() protoreflect.Message {
	mi := &file_output_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputFinding.ProtoReflect.Descriptor instead.
func (*OutputFinding) Descriptor() ([]byte, []int) {
	return file_output_policy_proto_rawDescGZIP(), []int{2}
}

func (x *OutputFinding) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OutputFinding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *OutputFinding) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *OutputFinding) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *OutputFinding) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *OutputFinding) GetScanner() string {
	if x != nil {
		return x.Scanner
	}
	return ""
}

func (x *OutputFinding) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *OutputFinding) GetMatchedPattern() string {
	if x != nil {
		return x.MatchedPattern
	}
	return ""
}

var File_output_policy_proto protoreflect.FileDescriptor

const file_output_policy_proto_rawDesc = "" +
	"\n" +
	"\x13output_policy.proto\x12\tcordum.v1\"\x8e\a\n" +
	"\x12OutputCheckRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x16\n" +
	"\x06tenant\x18\x03 \x01(\tR\x06tenant\x12A\n" +
	"\x06labels\x18\x04 \x03(\v2).cordum.v1.OutputCheckRequest.LabelsEntryR\x06labels\x12\x1d\n" +
	"\n" +
	"result_ptr\x18\x05 \x01(\tR\tresultPtr\x12#\n" +
	"\rartifact_ptrs\x18\x06 \x03(\tR\fartifactPtrs\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\b \x01(\tR\terrorCode\x12\x1b\n" +
	"\tworker_id\x18\t \x01(\tR\bworkerId\x12!\n" +
	"\fexecution_ms\x18\n" +
	" \x01(\x03R\vexecutionMs\x12*\n" +
	"\x11output_size_bytes\x18\v \x01(\x03R\x0foutputSizeBytes\x12!\n" +
	"\fcontent_hash\x18\f \x01(\tR\vcontentHash\x12\x1f\n" +
	"\vworkflow_id\x18\r \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\astep_id\x18\x0e \x01(\tR\x06stepId\x12%\n" +
	"\x0eoutput_content\x18\x0f \x01(\fR\routputContent\x12\"\n" +
	"\fcapabilities\x18\x10 \x03(\tR\fcapabilities\x12\x1b\n" +
	"\trisk_tags\x18\x11 \x03(\tR\briskTags\x12!\n" +
	"\fprincipal_id\x18\x12 \x01(\tR\vprincipalId\x12\x17\n" +
	"\apack_id\x18\x13 \x01(\tR\x06packId\x12!\n" +
	"\fcontent_type\x18\x14 \x01(\tR\vcontentType\x12Z\n" +
	"\x0foriginal_labels\x18\x15 \x03(\v21.cordum.v1.OutputCheckRequest.OriginalLabelsEntryR\x0eoriginalLabels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13OriginalLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xff\x01\n" +
	"\x13OutputCheckResponse\x125\n" +
	"\bdecision\x18\x01 \x01(\x0e2\x19.cordum.v1.OutputDecisionR\bdecision\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x17\n" +
	"\arule_id\x18\x03 \x01(\tR\x06ruleId\x12'\n" +
	"\x0fpolicy_snapshot\x18\x04 \x01(\tR\x0epolicySnapshot\x124\n" +
	"\bfindings\x18\x05 \x03(\v2\x18.cordum.v1.OutputFindingR\bfindings\x12!\n" +
	"\fredacted_ptr\x18\x06 \x01(\tR\vredactedPtr\"\xea\x01\n" +
	"\rOutputFinding\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x05 \x01(\x03R\x06length\x12\x18\n" +
	"\ascanner\x18\x06 \x01(\tR\ascanner\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x02R\n" +
	"confidence\x12'\n" +
	"\x0fmatched_pattern\x18\b \x01(\tR\x0ematchedPattern*g\n" +
	"\x0eOutputDecision\x12\x19\n" +
	"\x15OUTPUT_DECISION_ALLOW\x10\x00\x12\x1e\n" +
	"\x1aOUTPUT_DECISION_QUARANTINE\x10\x01\x12\x1a\n" +
	"\x16OUTPUT_DECISION_REDACT\x10\x022c\n" +
	"\x13OutputPolicyService\x12L\n" +
	"\vCheckOutput\x12\x1d.cordum.v1.OutputCheckRequest\x1a\x1e.cordum.v1.OutputCheckResponseB.Z,github.com/cordum/cordum/core/protocol/pb/v1b\x06proto3"

var (
	file_output_policy_proto_rawDescOnce sync.Once
	file_output_policy_proto_rawDescData []byte
)

func file_output_policy_proto_rawDescGZIP() []byte {
	file_output_policy_proto_rawDescOnce.Do(func() {
		file_output_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_output_policy_proto_rawDesc), len(file_output_policy_proto_rawDesc)))
	})
	return file_output_policy_proto_rawDescData
}

var file_output_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_output_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_output_policy_proto_goTypes = []any{
	(OutputDecision)(0),         // 0: cordum.v1.OutputDecision
	(*OutputCheckRequest)(nil),  // 1: cordum.v1.OutputCheckRequest
	(*OutputCheckResponse)(nil), // 2: cordum.v1.OutputCheckResponse
	(*OutputFinding)(nil),       // 3: cordum.v1.OutputFinding
	nil,                         // 4: cordum.v1.OutputCheckRequest.LabelsEntry
	nil,                         // 5: cordum.v1.OutputCheckRequest.OriginalLabelsEntry
}
var file_output_policy_proto_depIdxs = []int32{
	4, // 0: cordum.v1.OutputCheckRequest.labels:type_name -> cordum.v1.OutputCheckRequest.LabelsEntry
	5, // 1: cordum.v1.OutputCheckRequest.original_labels:type_name -> cordum.v1.OutputCheckRequest.OriginalLabelsEntry
	0, // 2: cordum.v1.OutputCheckResponse.decision:type_name -> cordum.v1.OutputDecision
	3, // 3: cordum.v1.OutputCheckResponse.findings:type_name -> cordum.v1.OutputFinding
	1, // 4: cordum.v1.OutputPolicyService.CheckOutput:input_type -> cordum.v1.OutputCheckRequest
	2, // 5: cordum.v1.OutputPolicyService.CheckOutput:output_type -> cordum.v1.OutputCheckResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_output_policy_proto_init() }
func file_output_policy_proto_init() {
	if File_output_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_output_policy_proto_rawDesc), len(file_output_policy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_output_policy_proto_goTypes,
		DependencyIndexes: file_output_policy_proto_depIdxs,
		EnumInfos:         file_output_policy_proto_enumTypes,
		MessageInfos:      file_output_policy_proto_msgTypes,
	}.Build()
	File_output_policy_proto = out.File
	file_output_policy_proto_goTypes = nil
	file_output_policy_proto_depIdxs = nil
}
