from typing import Any, Dict, Type, TypeVar, Tuple, Optional, BinaryIO, TextIO, TYPE_CHECKING

from typing import List


from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..models.edge_evaluate_request_layer import EdgeEvaluateRequestLayer
from ..types import UNSET, Unset
from typing import cast
from typing import cast, List
from typing import cast, Union
from typing import Dict
from typing import Union

if TYPE_CHECKING:
    from ..models.edge_evaluate_request_tool_input_redacted_type_0 import (
        EdgeEvaluateRequestToolInputRedactedType0,
    )
    from ..models.edge_evaluate_request_input_redacted_type_0 import (
        EdgeEvaluateRequestInputRedactedType0,
    )
    from ..models.edge_labels import EdgeLabels
    from ..models.edge_artifact_pointer import EdgeArtifactPointer


T = TypeVar("T", bound="EdgeEvaluateRequest")


@_attrs_define
class EdgeEvaluateRequest:
    """Redacted Edge action evaluation request for an existing session/execution. Do not send raw `tool_input`,
    `tool_result`, `raw_input`, `raw_transcript`, or `transcript`; send bounded `input_redacted`/`tool_input_redacted`
    plus `artifact_ptrs`.

        Attributes:
            principal_id (str):
            session_id (str):
            execution_id (str):
            layer (EdgeEvaluateRequestLayer):
            kind (str): Non-empty Edge event kind such as `hook.pre_tool_use`.
            event_id (Union[Unset, str]): Optional caller-supplied event ID; omitted values are generated by the server.
            tenant_id (Union[Unset, str]): Optional body tenant; when present it must match X-Tenant-ID.
            agent_product (Union[Unset, str]):
            tool_name (Union[Unset, str]): Hook tool name such as `Bash`; required for hook-layer tool evaluations.
            tool_use_id (Union[Unset, str]):
            input_redacted (Union['EdgeEvaluateRequestInputRedactedType0', None, Unset]): Bounded, redacted action input.
                The server re-redacts and computes the persisted `input_hash`.
            tool_input_redacted (Union['EdgeEvaluateRequestToolInputRedactedType0', None, Unset]): Claude-hook-friendly
                alias for `input_redacted`.
            input_hash (Union[Unset, str]): Optional client hash. When redacted input is supplied, the server
                computes/overwrites the persisted `sha256:` hash from accepted redacted input.
            tool_input_hash (Union[Unset, str]): Claude-hook-friendly alias for `input_hash`.
            cwd (Union[Unset, str]):
            repo (Union[Unset, str]):
            git_remote (Union[Unset, str]):
            git_branch (Union[Unset, str]):
            git_sha (Union[Unset, str]):
            action_name (Union[Unset, str]): Optional client hint; ignored/overridden by the server-side classifier when
                derivable.
            capability (Union[Unset, str]): Optional client hint; ignored/overridden by the server-side classifier when
                derivable.
            risk_tags (Union[Unset, List[str]]): Optional client hints. Server-side classifier output is authoritative.
            labels (Union[Unset, EdgeLabels]):
            artifact_ptrs (Union[Unset, List['EdgeArtifactPointer']]): References to redacted external artifacts for large
                or sensitive evidence.
            approval_ttl_seconds (Union[Unset, int]): Optional override of the default 5-minute approval TTL when policy
                returns REQUIRE_APPROVAL (EDGE-059). Bound to [1, 300] seconds
                server-side; values outside this range or omitted use the 5-minute
                default. Callers can ONLY shorten the TTL — values >300 are
                silently capped at the default. Used by e2e tests that need to
                exercise approval expiration inside a bounded sleep window.
                 Example: 2.
    """

    principal_id: str
    session_id: str
    execution_id: str
    layer: EdgeEvaluateRequestLayer
    kind: str
    event_id: Union[Unset, str] = UNSET
    tenant_id: Union[Unset, str] = UNSET
    agent_product: Union[Unset, str] = UNSET
    tool_name: Union[Unset, str] = UNSET
    tool_use_id: Union[Unset, str] = UNSET
    input_redacted: Union["EdgeEvaluateRequestInputRedactedType0", None, Unset] = UNSET
    tool_input_redacted: Union["EdgeEvaluateRequestToolInputRedactedType0", None, Unset] = UNSET
    input_hash: Union[Unset, str] = UNSET
    tool_input_hash: Union[Unset, str] = UNSET
    cwd: Union[Unset, str] = UNSET
    repo: Union[Unset, str] = UNSET
    git_remote: Union[Unset, str] = UNSET
    git_branch: Union[Unset, str] = UNSET
    git_sha: Union[Unset, str] = UNSET
    action_name: Union[Unset, str] = UNSET
    capability: Union[Unset, str] = UNSET
    risk_tags: Union[Unset, List[str]] = UNSET
    labels: Union[Unset, "EdgeLabels"] = UNSET
    artifact_ptrs: Union[Unset, List["EdgeArtifactPointer"]] = UNSET
    approval_ttl_seconds: Union[Unset, int] = UNSET
    additional_properties: Dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        from ..models.edge_evaluate_request_tool_input_redacted_type_0 import (
            EdgeEvaluateRequestToolInputRedactedType0,
        )
        from ..models.edge_evaluate_request_input_redacted_type_0 import (
            EdgeEvaluateRequestInputRedactedType0,
        )
        from ..models.edge_labels import EdgeLabels
        from ..models.edge_artifact_pointer import EdgeArtifactPointer

        principal_id = self.principal_id

        session_id = self.session_id

        execution_id = self.execution_id

        layer = self.layer.value

        kind = self.kind

        event_id = self.event_id

        tenant_id = self.tenant_id

        agent_product = self.agent_product

        tool_name = self.tool_name

        tool_use_id = self.tool_use_id

        input_redacted: Union[Dict[str, Any], None, Unset]
        if isinstance(self.input_redacted, Unset):
            input_redacted = UNSET
        elif isinstance(self.input_redacted, EdgeEvaluateRequestInputRedactedType0):
            input_redacted = self.input_redacted.to_dict()
        else:
            input_redacted = self.input_redacted

        tool_input_redacted: Union[Dict[str, Any], None, Unset]
        if isinstance(self.tool_input_redacted, Unset):
            tool_input_redacted = UNSET
        elif isinstance(self.tool_input_redacted, EdgeEvaluateRequestToolInputRedactedType0):
            tool_input_redacted = self.tool_input_redacted.to_dict()
        else:
            tool_input_redacted = self.tool_input_redacted

        input_hash = self.input_hash

        tool_input_hash = self.tool_input_hash

        cwd = self.cwd

        repo = self.repo

        git_remote = self.git_remote

        git_branch = self.git_branch

        git_sha = self.git_sha

        action_name = self.action_name

        capability = self.capability

        risk_tags: Union[Unset, List[str]] = UNSET
        if not isinstance(self.risk_tags, Unset):
            risk_tags = self.risk_tags

        labels: Union[Unset, Dict[str, Any]] = UNSET
        if not isinstance(self.labels, Unset):
            labels = self.labels.to_dict()

        artifact_ptrs: Union[Unset, List[Dict[str, Any]]] = UNSET
        if not isinstance(self.artifact_ptrs, Unset):
            artifact_ptrs = []
            for artifact_ptrs_item_data in self.artifact_ptrs:
                artifact_ptrs_item = artifact_ptrs_item_data.to_dict()
                artifact_ptrs.append(artifact_ptrs_item)

        approval_ttl_seconds = self.approval_ttl_seconds

        field_dict: Dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "principal_id": principal_id,
                "session_id": session_id,
                "execution_id": execution_id,
                "layer": layer,
                "kind": kind,
            }
        )
        if event_id is not UNSET:
            field_dict["event_id"] = event_id
        if tenant_id is not UNSET:
            field_dict["tenant_id"] = tenant_id
        if agent_product is not UNSET:
            field_dict["agent_product"] = agent_product
        if tool_name is not UNSET:
            field_dict["tool_name"] = tool_name
        if tool_use_id is not UNSET:
            field_dict["tool_use_id"] = tool_use_id
        if input_redacted is not UNSET:
            field_dict["input_redacted"] = input_redacted
        if tool_input_redacted is not UNSET:
            field_dict["tool_input_redacted"] = tool_input_redacted
        if input_hash is not UNSET:
            field_dict["input_hash"] = input_hash
        if tool_input_hash is not UNSET:
            field_dict["tool_input_hash"] = tool_input_hash
        if cwd is not UNSET:
            field_dict["cwd"] = cwd
        if repo is not UNSET:
            field_dict["repo"] = repo
        if git_remote is not UNSET:
            field_dict["git_remote"] = git_remote
        if git_branch is not UNSET:
            field_dict["git_branch"] = git_branch
        if git_sha is not UNSET:
            field_dict["git_sha"] = git_sha
        if action_name is not UNSET:
            field_dict["action_name"] = action_name
        if capability is not UNSET:
            field_dict["capability"] = capability
        if risk_tags is not UNSET:
            field_dict["risk_tags"] = risk_tags
        if labels is not UNSET:
            field_dict["labels"] = labels
        if artifact_ptrs is not UNSET:
            field_dict["artifact_ptrs"] = artifact_ptrs
        if approval_ttl_seconds is not UNSET:
            field_dict["approval_ttl_seconds"] = approval_ttl_seconds

        return field_dict

    @classmethod
    def from_dict(cls: Type[T], src_dict: Dict[str, Any]) -> T:
        from ..models.edge_evaluate_request_tool_input_redacted_type_0 import (
            EdgeEvaluateRequestToolInputRedactedType0,
        )
        from ..models.edge_evaluate_request_input_redacted_type_0 import (
            EdgeEvaluateRequestInputRedactedType0,
        )
        from ..models.edge_labels import EdgeLabels
        from ..models.edge_artifact_pointer import EdgeArtifactPointer

        d = src_dict.copy()
        principal_id = d.pop("principal_id")

        session_id = d.pop("session_id")

        execution_id = d.pop("execution_id")

        layer = EdgeEvaluateRequestLayer(d.pop("layer"))

        kind = d.pop("kind")

        event_id = d.pop("event_id", UNSET)

        tenant_id = d.pop("tenant_id", UNSET)

        agent_product = d.pop("agent_product", UNSET)

        tool_name = d.pop("tool_name", UNSET)

        tool_use_id = d.pop("tool_use_id", UNSET)

        def _parse_input_redacted(
            data: object,
        ) -> Union["EdgeEvaluateRequestInputRedactedType0", None, Unset]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                input_redacted_type_0 = EdgeEvaluateRequestInputRedactedType0.from_dict(data)

                return input_redacted_type_0
            except:  # noqa: E722
                pass
            return cast(Union["EdgeEvaluateRequestInputRedactedType0", None, Unset], data)

        input_redacted = _parse_input_redacted(d.pop("input_redacted", UNSET))

        def _parse_tool_input_redacted(
            data: object,
        ) -> Union["EdgeEvaluateRequestToolInputRedactedType0", None, Unset]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                tool_input_redacted_type_0 = EdgeEvaluateRequestToolInputRedactedType0.from_dict(
                    data
                )

                return tool_input_redacted_type_0
            except:  # noqa: E722
                pass
            return cast(Union["EdgeEvaluateRequestToolInputRedactedType0", None, Unset], data)

        tool_input_redacted = _parse_tool_input_redacted(d.pop("tool_input_redacted", UNSET))

        input_hash = d.pop("input_hash", UNSET)

        tool_input_hash = d.pop("tool_input_hash", UNSET)

        cwd = d.pop("cwd", UNSET)

        repo = d.pop("repo", UNSET)

        git_remote = d.pop("git_remote", UNSET)

        git_branch = d.pop("git_branch", UNSET)

        git_sha = d.pop("git_sha", UNSET)

        action_name = d.pop("action_name", UNSET)

        capability = d.pop("capability", UNSET)

        risk_tags = cast(List[str], d.pop("risk_tags", UNSET))

        _labels = d.pop("labels", UNSET)
        labels: Union[Unset, EdgeLabels]
        if isinstance(_labels, Unset):
            labels = UNSET
        else:
            labels = EdgeLabels.from_dict(_labels)

        artifact_ptrs = []
        _artifact_ptrs = d.pop("artifact_ptrs", UNSET)
        for artifact_ptrs_item_data in _artifact_ptrs or []:
            artifact_ptrs_item = EdgeArtifactPointer.from_dict(artifact_ptrs_item_data)

            artifact_ptrs.append(artifact_ptrs_item)

        approval_ttl_seconds = d.pop("approval_ttl_seconds", UNSET)

        edge_evaluate_request = cls(
            principal_id=principal_id,
            session_id=session_id,
            execution_id=execution_id,
            layer=layer,
            kind=kind,
            event_id=event_id,
            tenant_id=tenant_id,
            agent_product=agent_product,
            tool_name=tool_name,
            tool_use_id=tool_use_id,
            input_redacted=input_redacted,
            tool_input_redacted=tool_input_redacted,
            input_hash=input_hash,
            tool_input_hash=tool_input_hash,
            cwd=cwd,
            repo=repo,
            git_remote=git_remote,
            git_branch=git_branch,
            git_sha=git_sha,
            action_name=action_name,
            capability=capability,
            risk_tags=risk_tags,
            labels=labels,
            artifact_ptrs=artifact_ptrs,
            approval_ttl_seconds=approval_ttl_seconds,
        )

        edge_evaluate_request.additional_properties = d
        return edge_evaluate_request

    @property
    def additional_keys(self) -> List[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
