import { jsPDF } from "jspdf";
import type { AuditEntry, AuditCategory, AuditSeverity } from "../api/types";
import type { AuditFilters } from "../hooks/useAudit";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const PAGE_W = 210;
const PAGE_H = 297;
const M = 15;
const CW = PAGE_W - M * 2;
const FOOTER_H = 10;
const USABLE_H = PAGE_H - M - FOOTER_H;

const CATEGORY_LABELS: Record<string, string> = {
  safety_decision: "Safety Decision",
  human_action: "Human Action",
  system_event: "System Event",
  access_event: "Access Event",
};

const SEVERITY_LABELS: Record<string, string> = {
  high: "High",
  medium: "Medium",
  low: "Low",
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function filterSummary(filters: AuditFilters): string {
  const parts: string[] = [];
  if (filters.eventType?.length) parts.push(`Types: ${filters.eventType.join(", ")}`);
  if (filters.actor) parts.push(`Actor: ${filters.actor}`);
  if (filters.resourceType) parts.push(`Resource: ${filters.resourceType}`);
  if (filters.timeRange) parts.push(`Time: ${filters.timeRange}`);
  if (filters.search) parts.push(`Search: "${filters.search}"`);
  return parts.length > 0 ? parts.join(" | ") : "No filters applied";
}

function dateRange(events: AuditEntry[]): string {
  if (events.length === 0) return "No events";
  const sorted = events.map((e) => e.timestamp).sort();
  const from = sorted[0].slice(0, 10);
  const to = sorted[sorted.length - 1].slice(0, 10);
  return from === to ? from : `${from} to ${to}`;
}

function groupByDate(events: AuditEntry[]): Map<string, AuditEntry[]> {
  const groups = new Map<string, AuditEntry[]>();
  for (const e of events) {
    const date = e.timestamp.slice(0, 10);
    const list = groups.get(date) ?? [];
    list.push(e);
    groups.set(date, list);
  }
  return groups;
}

function countBy<T>(items: T[], key: (item: T) => string): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const item of items) {
    const k = key(item);
    counts[k] = (counts[k] ?? 0) + 1;
  }
  return counts;
}

// ---------------------------------------------------------------------------
// PDF generation
// ---------------------------------------------------------------------------

export async function generateAuditReport(
  events: AuditEntry[],
  filters: AuditFilters,
  user: string,
  onProgress?: (processed: number) => void,
): Promise<void> {
  const doc = new jsPDF("p", "mm", "a4");
  let y = M;

  const ensureSpace = (needed: number) => {
    if (y + needed > USABLE_H) {
      doc.addPage();
      y = M;
    }
  };

  // =========================================================================
  // PAGE 1: COVER
  // =========================================================================

  // Title
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30);
  doc.text("Cordum Audit Report", M, y + 30);

  // Divider
  doc.setDrawColor(60, 100, 240);
  doc.setLineWidth(1);
  doc.line(M, y + 35, M + 60, y + 35);

  // Date range
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80);
  doc.text(`Date Range: ${dateRange(events)}`, M, y + 48);

  // Filter summary
  doc.setFontSize(10);
  doc.text(`Filters: ${filterSummary(filters)}`, M, y + 56);

  // Generated info
  doc.text(`Generated by: ${user}`, M, y + 68);
  doc.text(`Generated at: ${new Date().toISOString()}`, M, y + 76);
  doc.text(`Total events: ${events.length}`, M, y + 84);

  // Footer branding
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text("Confidential — Cordum Platform Governance Record", M, PAGE_H - 20);

  // =========================================================================
  // PAGE 2: EXECUTIVE SUMMARY
  // =========================================================================

  doc.addPage();
  y = M;

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30);
  doc.text("Executive Summary", M, y);
  y += 10;

  // Category breakdown
  const catCounts = countBy(events, (e) => e.category ?? "system_event");
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60);
  doc.text("Events by Category", M, y);
  y += 6;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  for (const cat of ["safety_decision", "human_action", "system_event", "access_event"]) {
    const count = catCounts[cat] ?? 0;
    doc.setTextColor(80);
    doc.text(`${CATEGORY_LABELS[cat] ?? cat}: ${count}`, M + 4, y);
    y += 5;
  }
  y += 4;

  // Severity breakdown
  const sevCounts = countBy(events, (e) => e.severity ?? "low");
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60);
  doc.text("Events by Severity", M, y);
  y += 6;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  for (const sev of ["high", "medium", "low"]) {
    const count = sevCounts[sev] ?? 0;
    doc.setTextColor(sev === "high" ? 200 : 80, sev === "high" ? 50 : 80, sev === "high" ? 50 : 80);
    doc.text(`${SEVERITY_LABELS[sev]}: ${count}`, M + 4, y);
    y += 5;
  }
  y += 4;

  // Key highlights
  const denials = events.filter((e) => e.action?.includes("deny") || e.action?.includes("reject")).length;
  const policyChanges = events.filter((e) => e.resourceType === "policy_bundle" || e.resourceType === "policy_rule").length;
  const approvals = events.filter((e) => e.action?.includes("approve")).length;

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60);
  doc.text("Key Highlights", M, y);
  y += 6;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80);
  doc.text(`Total denials: ${denials}`, M + 4, y); y += 5;
  doc.text(`Policy changes: ${policyChanges}`, M + 4, y); y += 5;
  doc.text(`Approval decisions: ${approvals}`, M + 4, y); y += 5;

  // =========================================================================
  // PAGES 3+: EVENT LISTING
  // =========================================================================

  doc.addPage();
  y = M;

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30);
  doc.text("Event Listing", M, y);
  y += 10;

  const groups = groupByDate(events);
  const sortedDates = [...groups.keys()].sort();
  let processed = 0;

  for (const date of sortedDates) {
    const dayEvents = groups.get(date) ?? [];

    // Date header
    ensureSpace(12);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(40);
    doc.text(date, M, y);
    doc.setDrawColor(200);
    doc.setLineWidth(0.2);
    doc.line(M, y + 1, PAGE_W - M, y + 1);
    y += 6;

    for (const event of dayEvents) {
      ensureSpace(16);

      // Timestamp + category
      const time = event.timestamp.slice(11, 23);
      const cat = CATEGORY_LABELS[event.category ?? "system_event"] ?? "Event";

      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(100);
      doc.text(`${time}  [${cat}]`, M, y);

      // Severity indicator
      const sev = event.severity ?? "low";
      if (sev === "high") {
        doc.setTextColor(200, 50, 50);
        doc.text("HIGH", M + CW - 10, y);
      } else if (sev === "medium") {
        doc.setTextColor(200, 150, 30);
        doc.text("MED", M + CW - 8, y);
      }
      y += 4;

      // Event type + actor + resource
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40);
      const summary = `${event.eventType || event.action} — ${event.actor} → ${event.resourceType}:${event.resourceId}`;
      const truncSummary = summary.length > 100 ? summary.slice(0, 97) + "..." : summary;
      doc.text(truncSummary, M + 2, y);
      y += 4;

      // Message
      if (event.message) {
        doc.setFontSize(8);
        doc.setTextColor(80);
        const msgLines = doc.splitTextToSize(event.message, CW - 4) as string[];
        const displayLines = msgLines.slice(0, 2);
        doc.text(displayLines, M + 2, y);
        y += displayLines.length * 3.5;
      }

      // Mutation indicator
      if (event.snapshotBefore || event.snapshotAfter) {
        doc.setFontSize(7);
        doc.setFont("helvetica", "italic");
        doc.setTextColor(120);
        doc.text("[Content modified — before/after snapshots available]", M + 2, y);
        y += 3;
      }

      y += 2;
      processed++;
      if (processed % 20 === 0) {
        onProgress?.(processed);
        await new Promise((r) => setTimeout(r, 0));
      }
    }
  }

  onProgress?.(events.length);

  // =========================================================================
  // INTEGRITY FOOTER (last page)
  // =========================================================================

  ensureSpace(30);
  y += 6;
  doc.setDrawColor(60, 100, 240);
  doc.setLineWidth(0.5);
  doc.line(M, y, PAGE_W - M, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(40);
  doc.text("Integrity Statement", M, y);
  y += 5;

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80);
  const integrityLines = [
    "Events are append-only and immutable within the Cordum audit trail.",
    `Event ID range: ${events.length > 0 ? events[0].id : "N/A"} to ${events.length > 0 ? events[events.length - 1].id : "N/A"}`,
    `Total events in report: ${events.length}`,
    `Report generated: ${new Date().toISOString()}`,
  ];
  for (const line of integrityLines) {
    doc.text(line, M, y);
    y += 4;
  }

  // =========================================================================
  // PAGE NUMBERS
  // =========================================================================

  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${totalPages}`, PAGE_W / 2, PAGE_H - 6, { align: "center" });
    doc.text("Cordum Audit Report — Confidential", M, PAGE_H - 6);
  }

  // =========================================================================
  // SAVE
  // =========================================================================

  const dateStr = new Date().toISOString().slice(0, 10);
  doc.save(`cordum-audit-report-${dateStr}.pdf`);
}
