apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cordum.fullname" . }}-secrets
  labels:
    {{- include "cordum.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiKey: {{ required "secrets.apiKey is required" .Values.secrets.apiKey | quote }}
  {{- if .Values.secrets.adminPassword }}
  adminPassword: {{ .Values.secrets.adminPassword | quote }}
  {{- end }}
  {{- if and .Values.redis.auth.enabled (not .Values.redis.auth.existingSecret) }}
  redisPassword: {{ required "redis.auth.password is required when redis.auth.enabled=true and no existingSecret" .Values.redis.auth.password | quote }}
  {{- end }}
{{- if and (eq .Values.licensing.mode "token") .Values.licensing.token (not .Values.licensing.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cordum.licenseSecretName" . }}
  labels:
    {{- include "cordum.labels" . | nindent 4 }}
type: Opaque
data:
  license.json: {{ .Values.licensing.token | b64enc }}
{{- end }}
{{- if and .Values.nats.auth.token (not .Values.nats.auth.existingTokenSecret) }}
{{- $natsTokenKey := default "NATS_TOKEN" .Values.nats.auth.existingTokenSecretKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cordum.natsTokenSecretName" . }}
  labels:
    {{- include "cordum.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ $natsTokenKey }}: {{ .Values.nats.auth.token | quote }}
{{- end }}
{{- if .Values.auth.jwt.hmacSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cordum.jwtSecretName" . }}
  labels:
    {{- include "cordum.labels" . | nindent 4 }}
type: Opaque
stringData:
  hmacSecret: {{ .Values.auth.jwt.hmacSecret | quote }}
{{- end }}
{{- if and .Values.auth.saml.enabled .Values.auth.saml.cert .Values.auth.saml.key (not .Values.auth.saml.certSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cordum.fullname" . }}-saml
  labels:
    {{- include "cordum.labels" . | nindent 4 }}
type: kubernetes.io/tls
stringData:
  tls.crt: |-
{{ .Values.auth.saml.cert | nindent 4 }}
  tls.key: |-
{{ .Values.auth.saml.key | nindent 4 }}
{{- end }}
{{- if .Values.audit.export.webhook.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cordum.auditWebhookSecretName" . }}
  labels:
    {{- include "cordum.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret: {{ .Values.audit.export.webhook.secret | quote }}
{{- end }}
{{- if .Values.audit.export.datadog.apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cordum.auditDatadogSecretName" . }}
  labels:
    {{- include "cordum.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiKey: {{ .Values.audit.export.datadog.apiKey | quote }}
{{- end }}
